spring.application.name=trabalho-final

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=a33571043

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=500
logging.level.org.springframework.boot.devtools=DEBUG
