spring.application.name=trabalho-final

spring.datasource.url=jdbc:postgresql://db.rvzrnkdjvetiarvmwamy.supabase.co:5432/postgres?user=postgres&password=Tt173637
spring.datasource.username=tomastonial
spring.datasource.password=Tt173637

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=500
logging.level.org.springframework.boot.devtools=DEBUG
